# Generated by Django 3.2.4 on 2023-12-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Divya', '0002_auto_20231219_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_blog',
            name='Featured',
            field=models.IntegerField(choices=[(0, 'not_featured'), (1, 'Featured')], default=1),
        ),
        migrations.AlterField(
            model_name='my_portfolio',
            name='Featured',
            field=models.IntegerField(choices=[(0, 'not_featured'), (1, 'Featured')], default=1),
        ),
    ]
