# Generated by Django 3.2.4 on 2023-12-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Divya', '0003_auto_20231222_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_profile_nav',
            name='Featured',
            field=models.IntegerField(choices=[(0, 'not_featured'), (1, 'Featured')], default=1),
        ),
    ]
