# Generated by Django 3.2.4 on 2023-12-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Divya', '0004_my_profile_nav_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Certifictaion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_title', models.CharField(blank=True, max_length=300, null=True)),
                ('My_Certifictaion_short_dis', models.TextField(blank=True, max_length=600, null=True)),
                ('My_Certifictaion_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Certifictaion_link', models.URLField(blank=True, db_index=True, max_length=128, verbose_name='certificate_link')),
                ('Featured', models.IntegerField(choices=[(0, 'not_featured'), (1, 'Featured')], default=1)),
            ],
        ),
    ]
