# Generated by Django 3.2.4 on 2023-12-22 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Divya', '0005_my_certifictaion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('verification_link', models.URLField(blank=True, db_index=True, max_length=128, verbose_name='verification link')),
                ('date_earned', models.DateField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Divya.my_profile_nav')),
            ],
        ),
        migrations.DeleteModel(
            name='My_Certifictaion',
        ),
    ]
