# Generated by Django 3.2.4 on 2023-12-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Divya', '0006_auto_20231222_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='profile',
        ),
    ]
