# Generated by Django 3.2.4 on 2023-12-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Divya', '0007_remove_certification_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='date_earned',
        ),
        migrations.AddField(
            model_name='certification',
            name='Featured',
            field=models.IntegerField(choices=[(0, 'not_featured'), (1, 'Featured')], default=1),
        ),
    ]
