# Generated by Django 3.2.4 on 2023-12-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Divya', '0009_introduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos/%y')),
            ],
        ),
        migrations.DeleteModel(
            name='Introduction',
        ),
    ]
