# Generated by Django 3.2.4 on 2023-12-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Divya', '0010_auto_20231224_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_profile_nav',
            name='my_email',
            field=models.EmailField(blank=True, db_index=True, max_length=128, verbose_name='my_email'),
        ),
    ]
