# Generated by Django 3.2.4 on 2023-12-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_name', models.CharField(blank=True, max_length=100, null=True)),
                ('con_email', models.EmailField(blank=True, db_index=True, max_length=128, verbose_name='my_email')),
                ('con_message', models.TextField(blank=True, max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='My_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(blank=True, max_length=300, null=True)),
                ('blog_short_dis', models.TextField(blank=True, max_length=600, null=True)),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('blog_readtime', models.CharField(blank=True, max_length=100, null=True)),
                ('blog_publish_time', models.CharField(blank=True, max_length=100, null=True)),
                ('blog_medium_link', models.URLField(blank=True, db_index=True, max_length=128, verbose_name='blog_medium_link')),
                ('Featured', models.IntegerField(choices=[(0, 'not_featured'), (1, 'Featured')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='My_portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_title', models.CharField(blank=True, max_length=300, null=True)),
                ('portfolio_short_dis', models.TextField(blank=True, max_length=600, null=True)),
                ('portfolio_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('portfolio_readtime', models.CharField(blank=True, max_length=100, null=True)),
                ('portfolio_publish_time', models.CharField(blank=True, max_length=100, null=True)),
                ('portfolio_medium_link', models.URLField(blank=True, db_index=True, max_length=128, verbose_name='portfolio_medium_link')),
                ('portfolio_git_link', models.URLField(blank=True, db_index=True, max_length=128, verbose_name='portfolio_git_link')),
                ('portfolio_live_link', models.URLField(blank=True, db_index=True, max_length=128, verbose_name='portfolio_live_link')),
                ('Featured', models.IntegerField(choices=[(0, 'not_featured'), (1, 'Featured')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='My_profile_home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('my_job_status', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_intro', models.TextField(blank=True, max_length=600, null=True)),
                ('side_profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('what_i_do', models.TextField(blank=True, max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='My_profile_nav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('short_intro', models.CharField(blank=True, max_length=200, null=True)),
                ('side_profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('linkedin_link', models.URLField(blank=True, db_index=True, max_length=128, verbose_name='linkedin_link')),
                ('github_link', models.URLField(blank=True, db_index=True, max_length=128, verbose_name='github_link')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
